asset: https://confluence.infn.it/x/nYD8DQ
autosave_dir: /nfs/autosave/hazemeyer-serial-ch1
autosync: false
charturl: https://baltig.infn.it/epics-containers/ioc-chart.git
config_dir: /nfs/config/hazemeyer-serial-ch1
data_dir: /nfs/data/hazemeyer-serial-ch1
devgroup: mag
devices:
- id: '6'
  imax: '200'
  name: GUNSOL01
  vmax: '110'
  zones:
  - GUN
- id: '7'
  imax: '200'
  name: AC1SOL01
  vmax: '110'
  zones:
  - AC1
- id: '8'
  imax: '200'
  name: AC1SOL02
  vmax: '110'
  zones:
  - AC1
devtype: haz-ser
epik8s-tools-version: 0.9.12
iocname: hazemeyer-serial-ch1
iocprefix: SPARC:MAG:HZ
name: hazemeyer-serial-ch1
networks:
- annotation: sparc-magnets
  name: control
nfsMounts:
- mountPath: /nfs/data
  name: data
  opt: -o nolock
  path: /sparcstorage/space2/SparcData
  server: 192.168.197.157
- mountPath: /nfs/autosave
  name: autosave
  opt: -o nolock
  path: /data_epik8s/autosave
  server: 192.168.197.157
- mountPath: /nfs/config
  name: config
  opt: -o nolock
  path: /data_epik8s/config
  server: 192.168.197.157
opi: fastps
port: '4001'
server: 192.168.197.102
template: hazemeyer
